### All OK
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstName": "Alessio",
  "lastName": "Canestrelli",
  "email": "alessio.canestrelli@gmail.com"
}

### First name KO
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstName": "Al",
  "lastName": "Canestrelli",
  "email": "alessio.canestrelli@email.com"
}

### Last name KO
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstName": "Alessio",
  "lastName": "Ca",
  "email": "alessio.canestrelli@email.com"
}

### Email KO
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstName": "Alessio",
  "lastName": "Canestrelli",
  "email": "alessio.canestrelliemail.com"
}

### All KO
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstName": "Al",
  "lastName": "Ca",
  "email": "alessio.canestrelliemail.com"
}
